// Seeded once for new and reset workspaces; users own their organization afterward.
export const categoryDefinitions = [
  [
    "Income",
    "income",
    [
      ["Paycheck", "💵"],
      ["Interest", "🌱"],
      ["Business income", "💼"],
      ["Cash back & rewards", "🪙"],
      ["Resale", "🛒"],
      ["Other income", "✨"],
    ],
  ],
  [
    "Housing",
    "expense",
    [
      ["Rent", "🏡"],
      ["Home insurance", "🛡️"],
      ["Home improvement", "🔨"],
      ["Home maintenance", "🔧"],
      ["Cleaning", "🧹"],
    ],
  ],
  [
    "Bills & utilities",
    "expense",
    [
      ["Utilities", "💡"],
      ["Gas & electric", "⚡"],
      ["Water", "💧"],
      ["Garbage & recycling", "🗑️"],
      ["Phone", "📱"],
      ["Internet", "🌐"],
    ],
  ],
  [
    "Food & drink",
    "expense",
    [
      ["Groceries", "🥑"],
      ["Restaurants", "🍜"],
      ["Coffee", "☕"],
      ["Meal delivery", "🥡"],
      ["Meal kits", "🍱"],
      ["Snacks & vending", "🍫"],
      ["Convenience stores", "🏪"],
      ["Bars & drinks", "🍷"],
    ],
  ],
  [
    "Auto & transport",
    "expense",
    [
      ["Public transit", "🚇"],
      ["Fuel", "⛽"],
      ["Parking & tolls", "🅿️"],
      ["Car maintenance", "🔧"],
      ["Car payments", "🚙"],
      ["Auto insurance", "🛡️"],
      ["Rideshare & taxis", "🚕"],
      ["Bikes & scooters", "🚲"],
      ["Transport", "🚌"],
    ],
  ],
  [
    "Travel",
    "expense",
    [
      ["Flights", "✈️"],
      ["Accommodation", "🏨"],
      ["Ferries", "🧳"],
      ["Car rentals", "🚙"],
      ["eSIM & roaming", "📲"],
      ["Travel insurance", "☂️"],
      ["Tours & activities", "🗺️"],
      ["Souvenirs", "🏞️"],
      ["Travel", "🧳"],
    ],
  ],
  [
    "Shopping",
    "expense",
    [
      ["Shopping", "🛍️"],
      ["Clothing", "👕"],
      ["Furniture", "🪑"],
      ["Electronics", "🖥️"],
      ["Postage & shipping", "📦"],
    ],
  ],
  [
    "Health & wellness",
    "expense",
    [
      ["Fitness", "🏋️"],
      ["Pharmacy", "💊"],
      ["Haircuts", "✂️"],
      ["Dental", "🦷"],
      ["Doctor visits", "🩺"],
      ["Vision", "👓"],
      ["Toiletries", "🛁"],
      ["Health", "❤️"],
    ],
  ],
  [
    "Education",
    "expense",
    [
      ["Tuition & courses", "📚"],
      ["Books & learning materials", "📚"],
      ["Student loans", "🎓"],
    ],
  ],
  [
    "Entertainment",
    "expense",
    [
      ["Entertainment", "🎟️"],
      ["Video games", "🎮"],
      ["Movies & theater", "🎭"],
      ["Subscriptions", "🔄"],
      ["Hobbies & outdoors", "🏕️"],
    ],
  ],
  [
    "Family & pets",
    "expense",
    [
      ["Child care", "🧸"],
      ["Kids activities", "⚽"],
      ["Pets", "🐾"],
    ],
  ],
  [
    "Gifts & giving",
    "expense",
    [
      ["Gifts", "🎁"],
      ["Charity", "🎗️"],
    ],
  ],
  [
    "Financial",
    "expense",
    [
      ["Taxes", "🏛️"],
      ["Financial fees", "🏦"],
      ["Loan repayments", "📆"],
      ["Insurance", "🛡️"],
    ],
  ],
  ["Other", "expense", [["Uncategorized", "📁"]]],
  [
    "Transfers",
    "transfer",
    [
      ["Transfer", "↔️"],
      ["Credit card payment", "💳"],
      ["Loan principal", "📆"],
    ],
  ],
] as const;
